const APP_VERSION = '2.0.0';
const STORAGE_KEY = 'ceh-practice-v1';
const THEME_KEY = 'ceh-practice-theme';
const LETTERS = ['A','B','C','D'];
let QUESTIONS = [];
let view = 'home';
let currentId = null;
let selectedIndex = null;
let revealed = false;
let showTranslation = false;
let reviewFilter = 'all';
let exam = null;
let theme = document.documentElement.dataset.theme || 'light';

function defaultState(){return {version:APP_VERSION,answers:{},unknown:{},saved:{},history:[],todayGoal:30};}
function loadState(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return defaultState()}}
let state=loadState();
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function setTheme(next){theme=next==='dark'?'dark':'light';document.documentElement.dataset.theme=theme;try{localStorage.setItem(THEME_KEY,theme)}catch{}}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function sentences(text,locale){if(!text)return[];if(Intl?.Segmenter)return [...new Intl.Segmenter(locale,{granularity:'sentence'}).segment(text)].map(x=>x.segment.trim()).filter(Boolean);return text.match(/[^.!?。！？]+[.!?。！？]*|.+$/g)?.map(x=>x.trim()).filter(Boolean)||[text];}
function questionText(q){const en=sentences(q.question,'en'),zh=showTranslation?sentences(q.questionZh,'zh-Hant'):[],count=Math.max(en.length,zh.length);return `<div class="question-pairs ${showTranslation?'translation-visible':''}">${Array.from({length:count},(_,i)=>`<div class="sentence-pair">${en[i]?`<div class="sentence-row sentence-en"><span class="sentence-tag">EN</span><span>${esc(en[i])}</span></div>`:''}${zh[i]?`<div class="sentence-row sentence-zh" lang="zh-Hant"><span class="sentence-tag">中</span><span>${esc(zh[i])}</span></div>`:''}</div>`).join('')}</div>`;}
function optionText(q,i){return `<span><span>${esc(q.options[i])}</span>${showTranslation&&q.optionsZh?.[i]?`<span class="option-zh" lang="zh-Hant"><span class="language-label zh">中文</span>${esc(q.optionsZh[i])}</span>`:''}</span>`;}
function translationButton(q){const available=!!q.questionZh||q.optionsZh?.some(Boolean);return available?`<button class="btn btn-translate small" data-action="toggle-translation" aria-expanded="${showTranslation}">${showTranslation?'隱藏中文':'顯示中文'}</button>`:'';}
function explanationText(q){const letter=LETTERS[q.correctIndex];if(showTranslation)return (q.explanation||'').replace(/正確答案是\s*[A-D](?=[\s.．。])/gi,`正確答案是 ${letter}`).replace(/選項\s*[A-D](?=\s*(?:是)?正確)/gi,`選項 ${letter}`);return (q.explanationEn||'The source does not include an English explanation.').replace(/The correct answer is\s+[A-D](?=[\s.])/gi,`The correct answer is ${letter}`).replace(/Option\s+[A-D](?=\s+is correct)/gi,`Option ${letter}`);}
function qById(id){return QUESTIONS.find(q=>q.id===id)}
function isScorable(q){return q?.answerStatus==='source-verified'||q?.answerStatus==='web-verified';}
function answerStatusLabel(q){return q.answerStatus==='source-verified'?'來源答案':q.answerStatus==='web-verified'?'線上文件查證':q.answerStatus==='unverified'?'社群票選，尚未驗證':'來源未提供答案';}
function rec(id){return state.answers[id]||{correct:0,wrong:0,last:null,streak:0};}
function answeredCount(){return Object.keys(state.answers).length}
function totals(){let c=0,w=0;Object.values(state.answers).forEach(r=>{c+=r.correct||0;w+=r.wrong||0});return {c,w,n:c+w,acc:(c+w)?Math.round(c*100/(c+w)):0}}
function todayKey(){return new Date().toISOString().slice(0,10)}
function todayAnswered(){return state.history.filter(x=>x.date===todayKey()).length}
function level(id){const r=rec(id); if(state.unknown[id]) return '🔴 不熟'; if((r.wrong||0)>=(r.correct||0)) return r.wrong?'🔴 不熟':'⚪ 新題'; if((r.correct||0)>=3 && r.streak>=2) return '🟢 熟悉'; return '🟡 學習中';}
function chooseLearnQuestion(){
  const pool=QUESTIONS.map(q=>{const r=rec(q.id);let weight=1;if(!state.answers[q.id]) weight=9;if(state.unknown[q.id])weight+=8;if(r.wrong>r.correct)weight+=6;weight+=Math.max(0,3-(r.streak||0));return {q,weight}});
  const sum=pool.reduce((a,x)=>a+x.weight,0);let t=Math.random()*sum;for(const x of pool){t-=x.weight;if(t<=0)return x.q}return pool[0].q;
}
function recordAnswer(q,idx,mode='learn'){
  if(!isScorable(q))return null;
  const correct=idx===q.correctIndex; const r=rec(q.id); const nr={...r};
  if(correct){nr.correct=(nr.correct||0)+1;nr.streak=(nr.streak||0)+1;delete state.unknown[q.id]}else{nr.wrong=(nr.wrong||0)+1;nr.streak=0}
  nr.last=Date.now();state.answers[q.id]=nr;state.history.push({id:q.id,correct,date:todayKey(),mode,ts:Date.now()});
  if(state.history.length>3000)state.history=state.history.slice(-3000);save();return correct;
}
function markUnknown(id){state.unknown[id]=true;const q=qById(id);if(isScorable(q)){const r=rec(id);state.answers[id]={...r,wrong:(r.wrong||0)+1,streak:0,last:Date.now()};state.history.push({id,correct:false,unknown:true,date:todayKey(),mode:'learn',ts:Date.now()})}save();revealed=true;render();}
function toggleSaved(id){state.saved[id]=!state.saved[id];if(!state.saved[id])delete state.saved[id];save();render();}
function nav(){return `<nav class="bottom-nav"><div class="bottom-nav-inner">${[
 ['home','⌂','首頁'],['learn','▸','刷題'],['review','↻','複習'],['exam','◎','模擬考'],['stats','▥','統計']
].map(([v,i,t])=>`<button class="nav-btn ${view===v?'active':''}" data-nav="${v}"><strong>${i}</strong>${t}</button>`).join('')}</div></nav>`}
function shell(content){return `<main class="shell"><div class="topbar"><div><div class="brand">CEH v13 Practice</div><div class="sub">中英雙語題庫 · ${QUESTIONS.length} 題</div></div><div class="topbar-actions"><span class="pill">Offline Ready</span><button class="theme-toggle" data-action="toggle-theme" aria-label="${theme==='dark'?'切換至淺色模式':'切換至夜間模式'}" title="${theme==='dark'?'切換至淺色模式':'切換至夜間模式'}">${theme==='dark'?'☀️ 淺色':'🌙 夜間'}</button></div></div>${content}</main>${nav()}`}
function home(){const t=totals();const td=todayAnswered();const pct=Math.min(100,Math.round(td*100/state.todayGoal));
 const topic={};QUESTIONS.forEach(q=>{topic[q.topic]??={total:0,attempted:0,correct:0,tries:0};topic[q.topic].total++;if(state.answers[q.id])topic[q.topic].attempted++;const r=rec(q.id);topic[q.topic].correct+=r.correct||0;topic[q.topic].tries+=(r.correct||0)+(r.wrong||0)});
 return shell(`<section class="card hero"><div class="muted">Today's Goal</div><h1>${td} / ${state.todayGoal}</h1><div class="progress"><span style="width:${pct}%"></span></div><div style="height:14px"></div><button class="btn btn-primary full" data-action="continue">繼續學習</button></section>
 <div class="grid2"><section class="card"><div class="label">Accuracy</div><div class="metric">${t.acc}%</div><div class="muted small">${t.c} 對 / ${t.w} 錯</div></section><section class="card"><div class="label">Progress</div><div class="metric">${answeredCount()}/${QUESTIONS.length}</div><div class="muted small">已接觸題目</div></section></div>
 <div class="grid2"><button class="btn btn-outline" data-nav="review">錯題複習 ${Object.keys(state.unknown).length?'· '+Object.keys(state.unknown).length:''}</button><button class="btn btn-outline" data-action="saved">收藏題目 ${Object.keys(state.saved).length}</button></div>
 <div class="section-title">主題進度 <span class="muted small">（自動分類，僅供練習）</span></div><section class="card">${Object.entries(topic).sort((a,b)=>b[1].total-a[1].total).map(([k,v])=>{let a=v.tries?Math.round(v.correct*100/v.tries):0;return `<div class="topic-row"><div><strong>${esc(k)}</strong><div class="muted small">${v.attempted}/${v.total} 題已接觸</div></div><div><strong>${a}%</strong></div></div>`}).join('')}</section>`)}
function learn(){if(!currentId)currentId=chooseLearnQuestion().id;const q=qById(currentId);const r=rec(q.id);return shell(`<section class="card"><div class="qhead"><span class="pill">Q${q.id} · ${esc(q.topic)}</span><div class="q-actions">${translationButton(q)}<button class="btn btn-outline small" data-action="save">${state.saved[q.id]?'★ 已收藏':'☆ 收藏'}</button></div></div><div class="muted small">${level(q.id)} · ${isScorable(q)?`正確 ${r.correct||0} / 錯誤 ${r.wrong||0}`:'本題答案尚未驗證，不計分'}</div>${questionText(q)}${q.options.map((o,i)=>{let cls='option';if(selectedIndex===i)cls+=' selected';if(revealed&&i===q.correctIndex)cls+=isScorable(q)?' correct':' candidate';if(revealed&&selectedIndex===i&&i!==q.correctIndex&&isScorable(q))cls+=' wrong';return `<button class="${cls}" data-option="${i}" ${revealed?'disabled':''}><span class="letter">${LETTERS[i]}</span>${optionText(q,i)}</button>`}).join('')}
 ${revealed?resultBlock(q):`<div class="actions"><button class="btn btn-danger" data-action="unknown">我完全不會</button><button class="btn btn-primary" data-action="submit" ${selectedIndex===null?'disabled':''}>送出答案</button></div>`}</section>`)}
function resultBlock(q){const scorable=isScorable(q),ok=scorable&&selectedIndex===q.correctIndex,zh=showTranslation?q.optionsZh?.[q.correctIndex]:null;return `<div class="result ${scorable?(ok?'good':'bad'):'candidate'}"><strong>${scorable?(ok?'答對了':'答錯了'):'社群票選答案（尚未驗證、不計分）'}</strong><div class="answer">${scorable?'正確答案':'最高票選項'}：${LETTERS[q.correctIndex]}. ${esc(q.answerText)}${zh?`<span class="option-zh" lang="zh-Hant"><span class="language-label zh">中文</span>${esc(zh)}</span>`:''}</div><div class="muted small explanation-text" lang="${showTranslation?'zh-Hant':'en'}">${esc(explanationText(q))}</div><div class="source-note">來源：${esc(q.source)} #${q.sourceQuestionId} · ${answerStatusLabel(q)}</div></div><div class="actions"><button class="btn btn-outline" data-action="save">${state.saved[q.id]?'★ 已收藏':'☆ 收藏'}</button><button class="btn btn-dark" data-action="next">下一題</button></div>`}
function review(){let ids=QUESTIONS.filter(q=>{const r=rec(q.id);if(reviewFilter==='unknown')return !!state.unknown[q.id];if(reviewFilter==='wrong')return (r.wrong||0)>0;if(reviewFilter==='saved')return !!state.saved[q.id];return !!state.unknown[q.id]||(r.wrong||0)>0||!!state.saved[q.id]}).map(q=>q.id);
 return shell(`<div class="toolbar">${[['all','全部'],['unknown','完全不會'],['wrong','答錯'],['saved','收藏']].map(([k,t])=>`<button class="chip ${reviewFilter===k?'active':''}" data-review="${k}">${t}</button>`).join('')}</div><section class="card">${ids.length?ids.map(id=>{const q=qById(id),r=rec(id);return `<div class="list-item"><div class="num">${id}</div><div class="grow"><div class="truncate"><strong>${esc(q.question)}</strong></div><div class="muted small">${esc(q.topic)} · ${level(id)} · 對 ${r.correct||0}/錯 ${r.wrong||0}</div></div><button class="btn btn-outline small" data-open="${id}">練習</button></div>`}).join(''):`<div class="empty">目前沒有符合條件的題目。</div>`}</section>`)}
function stats(){const t=totals();const counts={};QUESTIONS.forEach(q=>{counts[q.topic]??={total:0,c:0,w:0,attempted:0};counts[q.topic].total++;const r=rec(q.id);if(state.answers[q.id])counts[q.topic].attempted++;counts[q.topic].c+=r.correct||0;counts[q.topic].w+=r.wrong||0});return shell(`<div class="grid2"><section class="card"><div class="label">Overall Accuracy</div><div class="metric">${t.acc}%</div></section><section class="card"><div class="label">Questions Seen</div><div class="metric">${answeredCount()}</div></section></div><section class="card"><div class="section-title" style="margin-top:0">主題統計</div>${Object.entries(counts).sort((a,b)=>(b[1].c+b[1].w)-(a[1].c+a[1].w)).map(([k,v])=>{const n=v.c+v.w,a=n?Math.round(v.c*100/n):0;return `<div class="topic-row"><div><strong>${esc(k)}</strong><div class="muted small">${v.attempted}/${v.total} 題 · ${n} 次作答</div></div><div class="${a>=75?'badge-good':a>=60?'badge-warn':'badge-bad'}"><strong>${a}%</strong></div></div>`}).join('')}</section><button class="btn btn-danger full" data-action="reset">清除所有學習紀錄</button>`)}
function examSetup(){const eligible=QUESTIONS.filter(isScorable).length;return shell(`<section class="card"><h2 style="margin-top:0">模擬考</h2><p class="muted">考試模式只使用答案已驗證的題目，送出後才計分。</p><label class="label">題數</label><select id="exam-count" class="option" style="display:block"><option value="25">25 題 · 快速測驗</option><option value="50">50 題</option><option value="125">125 題 · CEH 模擬考</option><option value="${eligible}">${eligible} 題 · 全部已驗證題目</option></select><div style="height:8px"></div><button class="btn btn-primary full" data-action="start-exam">開始模擬考</button></section>`)}
function examView(){if(!exam)return examSetup();if(exam.done)return examResult();const q=qById(exam.ids[exam.index]);const chosen=exam.answers[q.id];return shell(`<section class="card"><div class="exam-banner"><span class="pill">${exam.index+1}/${exam.ids.length}</span><div class="exam-tools">${translationButton(q)}<span class="timer">${formatTime(Math.floor((Date.now()-exam.started)/1000))}</span></div></div>${questionText(q)}${q.options.map((o,i)=>`<button class="option ${chosen===i?'selected':''}" data-exam-option="${i}"><span class="letter">${LETTERS[i]}</span>${optionText(q,i)}</button>`).join('')}<div class="exam-nav"><button class="btn btn-outline" data-action="exam-prev" ${exam.index===0?'disabled':''}>上一題</button><button class="btn btn-primary" data-action="exam-next">${exam.index===exam.ids.length-1?'送出考卷':'下一題'}</button></div></section>`)}
function examResult(){const rows=exam.ids.map(id=>{const q=qById(id);return {q,chosen:exam.answers[id],ok:exam.answers[id]===q.correctIndex}});const score=rows.filter(x=>x.ok).length;const pct=Math.round(score*100/rows.length);return shell(`<section class="card hero"><div class="muted">Mock Exam Score</div><h1>${score} / ${rows.length}</h1><div style="font-size:20px;font-weight:800">${pct}%</div></section><section class="card"><div class="section-title" style="margin-top:0">答錯題目</div>${rows.filter(x=>!x.ok).length?rows.filter(x=>!x.ok).map(x=>`<div class="list-item"><div class="num">${x.q.id}</div><div class="grow"><div class="truncate">${esc(x.q.question)}</div><div class="small badge-bad">你的答案：${x.chosen===undefined?'未作答':LETTERS[x.chosen]} · 正解：${LETTERS[x.q.correctIndex]}</div></div></div>`).join(''):`<div class="empty">全部答對。</div>`}</section><button class="btn btn-primary full" data-action="new-exam">再考一次</button>`)}
function formatTime(s){const m=Math.floor(s/60),ss=s%60;return `${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`}
function scrollToQuestionTop(){requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}));}
function startExam(n){const ids=QUESTIONS.filter(isScorable).sort(()=>Math.random()-.5).slice(0,n).map(q=>q.id);exam={ids,index:0,answers:{},started:Date.now(),done:false};showTranslation=false;render();}
function finishExam(){exam.done=true;exam.ids.forEach(id=>{const q=qById(id),idx=exam.answers[id];if(idx!==undefined)recordAnswer(q,idx,'exam')});render();}
function render(){let html=view==='home'?home():view==='learn'?learn():view==='review'?review():view==='exam'?examView():stats();document.getElementById('app').innerHTML=html;bind();}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;if(view==='learn'){if(!currentId)currentId=chooseLearnQuestion().id;showTranslation=false}render()});document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{if(!revealed){selectedIndex=+b.dataset.option;render()}});document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{reviewFilter=b.dataset.review;render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{currentId=+b.dataset.open;selectedIndex=null;revealed=false;showTranslation=false;view='learn';render()});document.querySelectorAll('[data-exam-option]').forEach(b=>b.onclick=()=>{const id=exam.ids[exam.index];exam.answers[id]=+b.dataset.examOption;render()});
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;let shouldScroll=false;if(a==='toggle-theme'){setTheme(theme==='dark'?'light':'dark');render();return}if(a==='toggle-translation'){showTranslation=!showTranslation;render();return}if(a==='continue'){view='learn';currentId=chooseLearnQuestion().id;selectedIndex=null;revealed=false;showTranslation=false}if(a==='saved'){view='review';reviewFilter='saved'}if(a==='save')toggleSaved(currentId);if(a==='unknown')markUnknown(currentId);if(a==='submit'){const q=qById(currentId);recordAnswer(q,selectedIndex,'learn');revealed=true}if(a==='next'){currentId=chooseLearnQuestion().id;selectedIndex=null;revealed=false;showTranslation=false;shouldScroll=true}if(a==='reset'){if(confirm('確定清除所有學習紀錄？此動作無法復原。')){state=defaultState();save()}}if(a==='start-exam'){startExam(+(document.getElementById('exam-count')?.value||25));return}if(a==='exam-prev'){exam.index=Math.max(0,exam.index-1);showTranslation=false;shouldScroll=true}if(a==='exam-next'){if(exam.index===exam.ids.length-1){if(confirm('確定送出考卷？')){finishExam();return}}else{exam.index++;showTranslation=false;shouldScroll=true}}if(a==='new-exam'){exam=null;showTranslation=false}render();if(shouldScroll)scrollToQuestionTop()})}
async function boot(){const res=await fetch('data/questions.json');QUESTIONS=await res.json();const requestedView=new URLSearchParams(location.search).get('view');if(['home','learn','review','exam','stats'].includes(requestedView)){view=requestedView;if(view==='learn')currentId=chooseLearnQuestion().id}render();if('serviceWorker'in navigator){const localHosts=new Set(['localhost','127.0.0.1','[::1]']);if(localHosts.has(location.hostname)){const registrations=await navigator.serviceWorker.getRegistrations();await Promise.all(registrations.map(registration=>registration.unregister()));if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(key=>caches.delete(key)))}}else navigator.serviceWorker.register('sw.js').catch(()=>{})}setInterval(()=>{if(view==='exam'&&exam&&!exam.done)render()},1000)}
boot();
